// Code generated by MockGen. DO NOT EDIT.
// Source: go-chromedp/app/store (interfaces: ICodeStore)

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICodeStore is a mock of ICodeStore interface.
type MockICodeStore struct {
	ctrl     *gomock.Controller
	recorder *MockICodeStoreMockRecorder
}

// MockICodeStoreMockRecorder is the mock recorder for MockICodeStore.
type MockICodeStoreMockRecorder struct {
	mock *MockICodeStore
}

// NewMockICodeStore creates a new mock instance.
func NewMockICodeStore(ctrl *gomock.Controller) *MockICodeStore {
	mock := &MockICodeStore{ctrl: ctrl}
	mock.recorder = &MockICodeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICodeStore) EXPECT() *MockICodeStoreMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockICodeStore) All(arg0 *context.Context) ([]CodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].([]CodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockICodeStoreMockRecorder) All(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockICodeStore)(nil).All), arg0)
}

// Create mocks base method.
func (m *MockICodeStore) Create(arg0 *context.Context, arg1 *CodeEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICodeStoreMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICodeStore)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockICodeStore) Delete(arg0 *context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICodeStoreMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICodeStore)(nil).Delete), arg0, arg1)
}

// FindByUDID mocks base method.
func (m *MockICodeStore) FindByUDID(arg0 *context.Context, arg1 string) ([]CodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUDID", arg0, arg1)
	ret0, _ := ret[0].([]CodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUDID indicates an expected call of FindByUDID.
func (mr *MockICodeStoreMockRecorder) FindByUDID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUDID", reflect.TypeOf((*MockICodeStore)(nil).FindByUDID), arg0, arg1)
}

// Get mocks base method.
func (m *MockICodeStore) Get(arg0 *context.Context, arg1 string) (*CodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*CodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockICodeStoreMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockICodeStore)(nil).Get), arg0, arg1)
}

// InitSchema mocks base method.
func (m *MockICodeStore) InitSchema() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitSchema")
}

// InitSchema indicates an expected call of InitSchema.
func (mr *MockICodeStoreMockRecorder) InitSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitSchema", reflect.TypeOf((*MockICodeStore)(nil).InitSchema))
}

// List mocks base method.
func (m *MockICodeStore) List(arg0 *context.Context, arg1, arg2 int) ([]CodeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]CodeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockICodeStoreMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockICodeStore)(nil).List), arg0, arg1, arg2)
}

// Total mocks base method.
func (m *MockICodeStore) Total(arg0 *context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MockICodeStoreMockRecorder) Total(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MockICodeStore)(nil).Total), arg0)
}

// Update mocks base method.
func (m *MockICodeStore) Update(arg0 *context.Context, arg1 *CodeEntity, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICodeStoreMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICodeStore)(nil).Update), arg0, arg1, arg2)
}

// Updates mocks base method.
func (m *MockICodeStore) Updates(arg0 *context.Context, arg1 *CodeEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockICodeStoreMockRecorder) Updates(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockICodeStore)(nil).Updates), arg0, arg1)
}
